version: "3.9"
services:
  postgres:
    container_name: entgen-postgres
    image: postgres:13.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d