// DO NOT EDIT
// This code was generated by github.com/hikaru7719/entgen

#[derive(sqlx::FromRow, Debug)]
pub struct Bools {
    pub aaa: bool,
}

use std::ops::Deref;
use std::sync::Arc;

pub struct BoolsRepository {
    pool: Arc<sqlx::PgPool>,
}

impl BoolsRepository {
    pub fn new(pool: Arc<sqlx::PgPool>) -> Self {
        BoolsRepository { pool: pool }
    }

    pub async fn insert(&self, bools: &Bools) -> Result<(), sqlx::Error> {
        sqlx::query("INSERT INTO bools (aaa) VALUES ($1)")
            .bind(bools.aaa)
            .execute(self.pool.deref())
            .await?;
        Ok(())
    }

    pub async fn find_all(&self) -> Result<Vec<Bools>, sqlx::Error> {
        Ok(sqlx::query_as::<_, Bools>("SELECT * FROM bools")
            .fetch_all(self.pool.deref())
            .await?)
    }
}
